server:
  port: 9051

spring:
  application:
    name: demo-feign-apiconsumer
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
feign:
  hystrix:
    enabled: true
  