server:
  port: 9003
spring:
  redis:
    database: 13
    port: 6379
    host: 192.168.226.133
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  application:
    name: sso-server